### ISSUE TITLE
Not being able to Uninstall Rebound Hub

### ISSUE THREAD

**Issue by WhaleStudiosDev** [IviriusMain/ReboundHub#1]
After Installing Rebound 11 (ReboundHub), I am not able to uninstall Rebound 11 to revert the changes. I did test it, but it was working a little bit and when I was going to uninstall it, It won't even let me even I'm running on the admin rights.
I uploaded this issue after testing this. (I know, it's a pre-release)

https://github.com/user-attachments/assets/84f76aa7-4fee-412a-8633-330ffc8341cc

**Comment by IviriusMain** [comment]
This feature is not yet supported in Rebound 11 and will be added in Rebound Hub v0.0.2 ALPHA.
(This issue will be closed after Rebound Hub v0.0.2 ALPHA is released.)
